### ISSUE TITLE
Why Facebook required?

### ISSUE THREAD

**Issue by jluttine** [nus-mtp/worldscope#87]
If WorldScope has its own servers, why does it use Facebook login? I'm worried about using Facebook to log into any service if it may (even in principle) mean that the service gets any access to my Facebook account.

Anyway, really interesting project! Is there some other place to discuss and ask questions? For instance, have you considered enabling gitter chat?

**Comment by ndt93** [comment]
Thank jluttine for your interests!

We were trying to make an open source clone of Periscope, which is integrated with Twitter; so we thought of using Facebook as an similar alternative that could support similar features such as sharing live streams, adding friends using Facebook friends list etc.

Login independent of Facebook should have been supported too. However we are doing this under the constraint of a semester university project and decided to implement higher priority requirements first i.e. social media integration.

Since this project has been concluded (for our university module), I suppose most existing developers will likely be inactive. Feel free to fork this repository if you plan to build any streaming service on top of this, or ask any question on this issue thread.

**Comment by jluttine** [comment]
Ok, thanks for the explanation! Sorry to hear the project has been concluded, would love to see this project flourishing. I hope some interested people will continue working on this. Anyway, thanks for your work!

**Comment by ndt93** [comment]
You're welcome and thanks for the kind words!
