### ISSUE TITLE
UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec

### ISSUE THREAD

**Issue by MhtSuthar** [nus-mtp/worldscope#91]
I am getting  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec while running android client on Android MarshMallow  devices. Can you please provide me any suggestion to overcome this?

**Comment by ndt93** [comment]
Hi @MhtSuthar, thank you for your interests. That could be due to incompatibility between JavaCV, the library we use for client streaming through rtmp and Android MarshMallow. We have only tested this on Android 4 and 5, so you might want to check if JavaCV has a newer version that works well with MarshMallow.

**Comment by MhtSuthar** [comment]
Hi @ndt93, I am able to make it work with Android MarshMallow, i used JavaCV 1.2 and javacpp 1.2.1 so, it fixed the issue. Also in process my application(MultiDex) was crashing due to some issues so i manually copeid all .so files in jniLibs and it worked. Thanks for your work.

**Comment by ndt93** [comment]
@MhtSuthar You're welcome. Glad you find this useful.
