### ISSUE TITLE
Requires facebook account = privacy issues

### ISSUE THREAD

**Issue by stemy2** [nus-mtp/worldscope#96]
Hello,

A facebook account is needed to connect cause there's not any other method, wich is unacceptable for privacy aware users.

**Comment by ndt93** [comment]
@stemy2 Hi stemy2, thanks for raising the issue. We did this as a university module project with the goal to provide a generic framework for developing live stream application. Thus, most parts are designed to be extensible including the authentication system. We develop a Facebook based OAuth as a demo/sample but you can extend it with any other solutions as well.

Also, this codebase has not been deployed as a product anywhere and we have not continued on this project since the module concluded. You can check another similar issue from the issues list for other discussions.
